tf-changes

diff --git a/.github/workflows/aws_tf_apply.yml b/.github/workflows/aws_tf_apply.yml
--- a/.github/workflows/aws_tf_apply.yml
+++ b/.github/workflows/aws_tf_apply.yml
@@ -46,11 +46,11 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: terraform plan
-        continue-on-error: true
+        #continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      #- name: Terraform Plan Status
+        #if: steps.plan.outcome == 'failure'
+        #run: exit 1
 
       - name: Terraform Apply
         run: terraform apply -auto-approve
diff --git a/.github/workflows/aws_tf_plan.yml b/.github/workflows/aws_tf_plan.yml
--- a/.github/workflows/aws_tf_plan.yml
+++ b/.github/workflows/aws_tf_plan.yml
@@ -46,8 +46,8 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: terraform plan
-        continue-on-error: true
+        #continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      #- name: Terraform Plan Status
+        #if: steps.plan.outcome == 'failure'
+        #run: exit 1
